CREATE TABLE attendees_events (
    id SERIAL NOT NULL PRIMARY KEY,
    id_event TEXT NOT NULL,
    id_attendee TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (id_event) REFERENCES events(id)
		ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_attendee) REFERENCES attendees(id)
		ON DELETE RESTRICT ON UPDATE CASCADE
);